[config]
schemaVersion = "0.0.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./BepInEx"
target = "./BepInEx"

[package]
namespace = "femboytv"
name = "femboytv"
versionNumber = "2.6.2"
description = "The best femboy modpack :3"
websiteUrl = "https://femboy.tv"
containsNsfwContent = false

[publish]
repository = "https://thunderstore.io"
communities = [ "lethal-company", ]

[publish.categories]
lethal-company = [ "bepinex", "modpacks", ]

[package.dependencies]
femboytv-FemboyTV_Posters = "3.0.0"
femboytv-FemboyTV_QoL = "3.0.0"
femboytv-FemboyTV_Suits = "3.0.0"
# Our haptics mod
LethalPlugging-LethalVibrations = "0.0.8"
LethalPlugging-LethalHaptics = "0.0.5"
# Other mods
2018-LC_API = "3.3.2"
AllToasters-SpectateEnemies = "2.2.1"
BeansDev-Neofetch = "1.0.5"
Bibendi-AEIOUCompany = "1.3.5"
Drakorle-MoreItems = "1.0.2"
EladNLG-EladsHUD = "1.2.1"
EliteMasterEric-Coroner = "1.5.3"
EliteMasterEric-SlimeTamingFix = "1.0.2"
Evaisa-LethalLib = "0.13.0"
Evaisa-LethalThings = "0.9.4"
FlipMods-LetMeLookDown = "1.0.1"
Krayken-DynamicDeadline = "1.2.2"
LRC-LRCCosmetics = "1.3.0"
MassiveNewCoilers-FixCentipedeLag = "2023.12.7"
Midge-PushCompany = "1.2.0"
NiceHairs-Symbiosis = "1.0.5"
NotAtomicBomb-TerminalApi = "1.5.0"
NotAtomicBomb-Terminal_History = "1.0.4"
Ozone-BepInUtils = "1.2.1"
Ozone-Disregard_Early_Voting = "1.0.2"
Renegades-FlashlightToggle = "1.5.0"
Renegades-WalkieUse = "1.4.0"
Rune580-LethalCompany_InputUtils = "0.5.5"
Sligili-More_Emotes = "1.3.3"
Suskitech-AlwaysHearActiveWalkies = "1.4.4"
Sv_Matt-HideModList = "1.0.1"
TwinDimensionalProductions-CoilHeadStare = "1.0.3"
kRYstall9-FastSwitchPlayerViewInRadar = "1.3.2"
notnotnotswipez-MoreCompany = "1.7.4"
taffyko-NameplateTweaks = "1.0.6"
tinyhoot-ShipLobby = "1.0.2"
tinyhoot-ShipLoot = "1.0.0"
x753-Mimics = "2.3.2"
xCeezy-LethalEscape = "0.8.5"
