[config]
schemaVersion = "0.0.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./BepInEx"
target = "./BepInEx"

[package]
namespace = "femboytv"
name = "femboytv"
versionNumber = "3.0.2"
description = "The best femboy modpack :3"
websiteUrl = "https://femboy.tv"
containsNsfwContent = false

[publish]
repository = "https://thunderstore.io"
communities = [ "lethal-company", ]

[publish.categories]
lethal-company = [ "bepinex", "modpacks", ]

[package.dependencies]
femboytv-FemboyTV_Posters = "3.0.2"
femboytv-FemboyTV_QoL = "3.0.2"
femboytv-FemboyTV_Suits = "3.0.2"
# Our haptics mod
LethalPlugging-LethalVibrations = "0.0.8"
LethalPlugging-LethalHaptics = "0.0.5"
# Other mods
2018-LC_API = "3.4.5"
AllToasters-SpectateEnemies = "2.4.1"
BeansDev-Neofetch = "1.0.5"
Bibendi-AEIOUCompany = "1.3.6"
Drakorle-MoreItems = "1.0.2"
EladNLG-EladsHUD = "1.2.1"
EliteMasterEric-Coroner = "1.6.2"
EliteMasterEric-SlimeTamingFix = "1.0.2"
Evaisa-LethalLib = "0.15.1"
Evaisa-LethalThings = "0.10.4"
FlipMods-LetMeLookDown = "1.0.1"
Krayken-DynamicDeadline = "1.2.2"
LRC-LRCCosmetics = "1.3.0"
MassiveNewCoilers-FixCentipedeLag = "2023.12.7"
Midge-PushCompany = "1.2.0"
NiceHairs-Symbiosis = "1.0.5"
NotAtomicBomb-TerminalApi = "1.5.4"
NotAtomicBomb-Terminal_History = "1.0.5"
Ozone-BepInUtils = "1.2.1"
Ozone-Disregard_Early_Voting = "1.0.2"
Rune580-LethalCompany_InputUtils = "0.7.4"
Sligili-More_Emotes = "1.3.3"
Sv_Matt-HideModList = "1.0.1"
TwinDimensionalProductions-CoilHeadStare = "1.0.9"
kRYstall9-FastSwitchPlayerViewInRadar = "1.3.2"
notnotnotswipez-MoreCompany = "1.9.1"
taffyko-NameplateTweaks = "1.0.6"
tinyhoot-ShipLobby = "1.0.2"
tinyhoot-ShipLoot = "1.1.0"
x753-Mimics = "2.5.0"
xCeezy-LethalEscape = "0.8.5"
